// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAANlfG82EembQLETC5lqolloxTaXhjnaU',
    appId: '1:279924491371:web:f3ab651c33cc3ce451dd2e',
    messagingSenderId: '279924491371',
    projectId: 'who-knows-sagar',
    authDomain: 'who-knows-sagar.firebaseapp.com',
    storageBucket: 'who-knows-sagar.firebasestorage.app',
    measurementId: 'G-FYXQB093EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRioPGmRs97wl04OvK_DHBKdaiEAzkui0',
    appId: '1:279924491371:android:1547b652d3bf7b6a51dd2e',
    messagingSenderId: '279924491371',
    projectId: 'who-knows-sagar',
    storageBucket: 'who-knows-sagar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7NfomtEsDht6CTrsnrG8HtM3PnJo9vI',
    appId: '1:279924491371:ios:05c9e6664d04ff0151dd2e',
    messagingSenderId: '279924491371',
    projectId: 'who-knows-sagar',
    storageBucket: 'who-knows-sagar.firebasestorage.app',
    iosBundleId: 'com.satyam.whoknowssagar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAANlfG82EembQLETC5lqolloxTaXhjnaU',
    appId: '1:279924491371:web:ff08c1e114472fdb51dd2e',
    messagingSenderId: '279924491371',
    projectId: 'who-knows-sagar',
    authDomain: 'who-knows-sagar.firebaseapp.com',
    storageBucket: 'who-knows-sagar.firebasestorage.app',
    measurementId: 'G-1LT6MQXBX4',
  );
}
